from tabulate import tabulate
import csv

texts = [
    "100 Most Anticipated books releasing in 2010",
    "10 best films of 2009 - What's on your list?",
    "10 days of free admission at Lan Su Chinese Garden to celebrate their 10th birthday",
    "10 PlayStation games to watch out for in 2010",
    "10 resolutions for a Happy New Year for you and your dachshund",
    "10 Tips to a healthy diet that works",
    "10 tips to avoid the drive-thru and encourage weight loss",
    "10 trends to end in 2010",
    "11 year-old girl and 15 year-old boy accused of attempting to kill mother: Who is the adult?",
    "12 Days of Rotoff: Vijay Singh",
    "12 New Year's resolutions for better eating",
    "14 Hours of Energy Conference",
    "Entertainment farewells",
    "In Review: Lacrosse inches into the mainstream",
    "Review: Climategate to Copenhagen Part I",
    "Best pet moments for me",
    "Sprint Cup season in review: Clint Bowyer",
    "The Year in Viral Videos, a Retrospective' covers all the bases (with funny video)",
    "Top 10 Christian Fiction Atlanta Based Authors Announced",
    "Adam Lambert's year to star: 2010 should be bigger (video & slide show)",
    "2009 was a year of great tunes and great shows",
    "Weather Highlights",
    "And beyond, beyond ...",
    "A New Year and a new decade dawns: What dreams will come, what will we do?",
    "A space fairy tale",
    "A Whole New Year",
    "A year of races ... GOP Gov. race",
    "Ball drop video from Times Square - Happy New Year 2010!",
    "California fishing license: No Wear initiative, voluntary Warden Stamp, Delta Bay Stamp gone",
    "California restaurant law: No more trans fats in restaurant cooking",
    "Challenge yourself to save money",
    "Coupin schedule is now available for you to plan your newspaper purchases",
    "Fitness trend: get fit with Wii Fit",
    "Grammy Awards: Best Contemporary R&B Album prediction & analysis",
    "Heavy Music Preview",
    "How do you say it, 'twenty ten' or 'two-thousand ten'?",
    "Is the Year of the Tiger",
    "Make it your best year ever!",
    "New Year resolutions for dog owners",
    "New Year's Resolution: Attend the Benson's Flea Market and Antique Show",
    "NLL preview: Philadelphia Wings",
    "Pierce County elections - County level",
    "Predictions by Post Road Advisors",
    "Scholarship Listings",
    "First Pop of King gives us the author's 10 best movies of 2009",
    "First UFC event to be held Saturday",
    "The future is here and I want my money back!",
    "The Top 5 Albums of the past Decade - Nico Stai",
    "Volunteer vacations and opportunities in Arizona",
    "Wardrobe Essentials: Platform Sandals and Flats",
    "Mistakes to avoid when making weight loss resolutions",
    "Steps to turn your resolution into results",
    "Winter cycling products to keep you warm and dry",
    "Clean recipes to start the New Year",
    "Days of Disney on Ice in Long Beach, CA",
    "New Year resolutions for teen parents",
    "Penguins named to Olympic rosters",
    "Simple New Year's resolutions you can keep",
    "Tips to credit card identity theft prevention",
    "Ways to save $500 in 2010",
    "60 second success tip: blind marching band leads the way",
    "Shop for retro super hero garb",
    "Job search resolutions for 2010",
    "Month-old Arizona boy Gabriel Johnson still missing after mother's arrest in Miami Beach",
    "Tips to refresh your relationship in the New Year",
    "Aamir Khan's 3 Idiots breaks all box office records, earns Rs.100 crores in 4 days - watch online",
    "A better you equals better prospects",
    "A Black Tie Affair",
    "A broken rosary",
    "Acer unveiling laptop at CES 2010 with new Intel Technology and boasting a 10 hour battery",
    "ACLS classes in central and eastern Virginia - updated January 1, 2010",
    "A College Students Guide To Disney World: Hollywood Studios",
    "A connection that's ... Thicker than Blood",
    "A cool wet December for most of California",
    "A cynic's look back",
    "Adam Lambert flashed by Pamela Anderson on New Year's Eve: Nude breast a free show - photo",
    "Adam Lambert Gridlock performance on New Year's Eve (video)",
    "Adam Lambert is stylish and 'shiny' at Gridlock's New Year's Eve Bash (photo slideshow and video)",
    "Adam Lambert on New Year's Eve: No New York TV, see his LA Gridlock performance here (video)",
    "Adam Lambert performing at Gridlock (watch video here) Sleepwalker",
    "Adam Lambert rocked the red carpet and stage at Gridlock New Year's Eve party (photos, video)",
    "Adam Lambert too risky for Rockin' New Year's Eve, but Jennifer Lopez's outfit outrageous (video)",
    "A Decade in Flames - Top 10 Moments",
    "A decade of indie",
    "A decade of unforgettable designers",
    "A delicious dip recipe - spinach and parmesan cheese",
    "A different take on 2009",
    "Aerial fireworks display from the backyard",
    "A few more changes that yield big results - part 3",
    "A few New Year's resolutions for the Bucs",
    "Afghan suicide bomber update: CIA revenge, Afghan National Army, invited on Afghanistan base (video)",
    "A green pet",
    "A harried experience of traveling with Fido during the Christmas rush",
    "A healthy New Year",
    "A highlight of what happened in the transportation industry in 2009",
    "Air Force uses ground attack to beat Houston in Armed Forces Bowl",
    "Airline delays on the tarmac - the rules are changing",
    "Airport pat-downs not effective",
    "A law enforcement officer is asked to predict the future of medical marijuana in Colorado for 2010",
    "Albania: Prime Minister Sali Berisha is the most successful leader in Europe",
    "Albuquerque palmist forecasts 2010 for writers",
    "Alfred Hitchcock thrillers Sundays on BBC",
    "Alganon state of the game - December",
    "Al Hoang Inauguration Reception",
    "A life coach can help you make those New Year's resolutions come true",
    "A life lesson for Tiger",
    "Aliso Creek restoration stakeholders hoping for federal stimulus dollars",
    "All-Day New Years Brunch at Goose Island Clybourn",
    "A look at a Taliban New Year",
    "A look back at 2009's cancelled TV shows and a glimpse ahead at what 2010 holds in store",
    "Alternative healing for horses? How about a magnet!",
    "Amanda Knox conviction leads to Seattle scrapping 'Perugia' as name for new park",
    "A Medieval Themed Wedding part 2 The Wedding Apparel on Wedding Fashion Friday!",
    "Americana Vineyards and Crystal Lake Cafe: Wine Tasting on Lake Cayuga in the Finger Lakes Region",
    "'American Idol:' Adam Lambert chats with reporters before performance",
    "'American Idol:' Kris Allen hits up Las Vegas",
    "'American Idol:' see Adam Lambert's New Year's Eve performance",
    "American Idol's new season",
    "Amo Joy tour begins today",
    "A Multicultural Celebration of New Years in Washington DC",
    "Anatomy of a couple squabble that could have become a war",
    "A new God both Atheists and Theists can believe in",
    "A new idea for your vacation - voluntourism",
    "A New Year and a new slate",
    "A new year, a new location",
    "A new year fresh start with free on demand yoga",
    "A new year in gaming",
    "A New Year's Resolution Diet Primer",
    "A New Year's resolution for activists",
    "A New Year's Resolution for an Allergy-Friendly Year",
    "A New Year's resolution to get your art degree at a school in Austin",
    "Angeleana M. Walker is missing girl in Spokane, Washington",
    "Angelina Jolie wins title of 'Beauty Icon of the Decade' in the U.K.",
    "An interview with Minnesota homeschool mother and author Erica Vetsch",
    "Annual New Years 'Twilight Zone' marathon on the Syfy channel",
    "Another outstanding effort wasted in loss to Lakers",
    "Anticipating new fiction books in 2010",
    "Antiques & auction marketplace predictions for 2010",
    "ANTM winner Whitney Thompson takes on Crystal Renn in plus-size model market",
    "An updated history of San Francisco climate",
    "Aoki breaks Hirato arm (video), not for the weak of heart",
    "A Perfect Ten ...",
    "A positive attitude creates positive pet grooming",
    "Apple Boot Camp users frustrated over Windows 7 support delay",
    "Apple Pancake - a weekend treat",
    "Arctic air locks in over region; Lake effect snow warning for northern Indiana and SW Michigan",
    "Are fights over food & nutrition the number one cause that sends gals to abused spouses shelters?",
    "Arenas, Crittenton pull guns Christmas Eve",
    "Aren't Coaches supposed to be teachers?",
    "Are there more bacteria on blown-on birthday cakes and in machine-made ice than in toilets?",
    "Arizona Republican Party wants no change: McCain again?",
    "Arizona's resurrection Mary",
    "Arizona Wildcats fall to USC in Pac-10 basketball opener",
    "Armored",
    "Arrest and release Rabbi Meir Kahane grandson for West Bank mosque fire",
    "Arrests made by Ecorse police in drug-related killing of Keon Butcher",
    "'Art After Five' at the Philadelphia Art Museum",
    "Artists to keep an eye on in 2010",
    "Ashley Jo Beach",
    "Mayo Clinic in Arizona drops most Medicare patients",
    "Assessing Obama's 2009 foreign policy: time for him to walk the talk",
    "As temperatures fall, so do room rates at The Colonnade Hotel, Boston",
    "As the pendulum swings ...",
    "ATA-CODEGA offer driver training materials",
    "A tale of two Presidents",
    "A toast to J.R.R. Tolkien for his January 3 birthday - author of faith-based Lord of the Rings",
    "A Travel Photographer's New Year's Resolution for 2010",
    "Attempted bombing is just another in long list of mistakes Obama and his administration make",
    "A Twilight party for your New Year's Eve celebration",
    "Anxiety starts to emerge in Peru on the Amazon laws",
    "An exciting year for baseball in Michigan in 2010",
    "An expensive heart procedure isn't always best",
    "A once-a-week date night, too much",
    "Apes in space",
    "Apologetic internet home decorators unite",
    "Aqua blue becomes new black for hair color",
    "Are funds for international initiatives in health the best use of our dollars?",
    "Are seasonal allergies the same as hay fever?",
    "Are you ready to kill someone?",
    "Arizona prison escape: two of the escaped inmates captured, third remains on the loose",
    "Arizona's prison escapees update: inmates held on previous charges, officials rule out terrorism",
    "Arizona staycation: geocaching is a great family event",
    "Arrogance in NFL playoffs doesn't pay",
    "Artificial intelligence making a real impact in science fiction movies",
    "Are you frustrated with your MacBook Pro because it won't eject your CD?",
    "Are your pets ready for 2010?",
    "Arsenal welcome re-arranged Villa match",
    "Art treasures worth millions, taken from Warsaw during World War II, found in Ukraine",
    "Artwork: The Fine Art of Eddie Cambier",
    "As a decade of television ends ...",
    "As an NFL decade ends ...",
    "Ascension Day, the start of the Christian liturgical season of Eastertide, observed by churches",
    "A Santa Monica New Year's Day beach party for young and old",
    "A Santa Monica New Year's Day beach party for young and old",
    "As Obama heads to Hawaii for vacation, campaign era assurances left unmet",
    "As part of my New Year's resolution to be more timely, I was late filing this report",
    "Artists weigh in on the past decade",
    "Ask a hypnotherapist: overcome your fear of flying",
    "Ask yourself: Are you ready for a puppy?",
    "Asks Attorney General Jerry Brown to investigate Rancho Cordova's illegal dumping",
    "Asian Lunar New Year 2010 arrives Valentine's Day",
    "As the New Year arrives, a cold front comes along for the ride",
    "A unique way to recycle old Holiday cards",
    "An unusual Christmas Day in Salt Lake City",
    "Apple's $9.99 e-book price may be low, but it adds up to the best deal around",
    "Apple's holiday app sales: top 5 bestsellers",
    "A poem for the New Year: 'Do not stand at my grave and weep'",
"App of the Week: Super Mom picks the best free app for iPhone, iPad and Android",
]

def analyze_sentiment(text):
    if "win" in text:
        return "positive"
    elif "free" in text:
        return "neutral"
    elif "pampalaki" in text:
        return "clickbait"
    else:
        return "neutral"    

def perform_semantic_analysis(text):
    return len(text.split())

data = []

for text in texts:
    sentiment = analyze_sentiment(text)

    semantic_analysis = perform_semantic_analysis(text)
    tag = "genuine" if sentiment == "neutral" else "clickbait"

    data.append([text, tag, sentiment, semantic_analysis, semantic_analysis, semantic_analysis])

headers = ["Headline", "Tag", "Sentiment", "SSA", "SSAM", "SSAT"]

with open('output.csv', mode='w', newline='') as csv_file:
    writer = csv.writer(csv_file)
    writer.writerow(headers)  
    writer.writerows(data) 
